### ISSUE TITLE
[BUG][1.9.15] Uncaught TypeError: prop.indexOf is not a function

### ISSUE THREAD

**Issue by Anima-t3d** [ManuelDeLeon/viewmodel#123]
Existing code no longer works with VM v1.9.15 giving `Uncaught TypeError: prop.indexOf is not a function` error.

**Comment by ManuelDeLeon** [comment]
Give me the element with the bind and the value of the property it's bound to.

**Comment by lucidprogrammer** [comment]
I also get this error whenever I use the attr binding. For example, 

```
data-bind="value: titleValue, attr: { name: titleValue }" 
data-bind="value: titleValue, attr: { placeholder: titleValue }"
```

A fix is really appreciated. Let me know if you need any further info.

**Comment by Anima-t3d** [comment]
@lucidprogrammer yes I think I have the same issue here. I am working on a big project and it seems to be present pretty much everywhere so it is hard to pinpoint. So I am quite confident that it is caused by the attr binding.

**Comment by ManuelDeLeon** [comment]
My brain is fried now. I'll fix it tomorrow.

**Comment by ManuelDeLeon** [comment]
Should be fine with 1.9.16
Sorry about that.

**Comment by Anima-t3d** [comment]
Ok thanks. Seems to be working again.

**Comment by lucidprogrammer** [comment]
Wonderful, excellent speed of response Manuel
